// This file was generated by running "npm run templates"
export const lines = [
    '<h1 class="heading">Bookmarks</h1>',
    '<p class="description">',
    '    Bookmarks is an example of taking an idea from concept to delivery as a full stack project. Implemented with',
    '    Angular on the front-end, and NodeJS on the back-end.',
    '</p>',
    '<div class="bookmark-image"></div>',
    '<!--',
    '<img src="/assets/images/bookmarks-sample.jpg" alt="Image">',
    '-->',
    '<div class="footer">',
    '    <a class="btn btn-primary" href="http://bookmarks.reactgular.com/">View Live Demo</a>',
    '</div>',
    ''
];
